"""added encryption

Revision ID: 89fb3fe126e0
Revises: 200042fe78c1
Create Date: 2025-07-06 22:23:29.427186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '89fb3fe126e0'
down_revision: Union[str, Sequence[str], None] = '200042fe78c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('mobile', sa.VARBINARY(length=100), nullable=True))
    op.alter_column('authors', 'name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.VARBINARY(length=100),
               existing_nullable=True)
    op.create_index(op.f('ix_authors_mobile'), 'authors', ['mobile'], unique=True)
    op.add_column('books', sa.Column('publisher_name', sa.VARBINARY(length=200), nullable=True))
    op.add_column('books', sa.Column('price', sa.Integer(), nullable=True))
    op.alter_column('books', 'title',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.VARBINARY(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'title',
               existing_type=sa.VARBINARY(length=200),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_column('books', 'price')
    op.drop_column('books', 'publisher_name')
    op.drop_index(op.f('ix_authors_mobile'), table_name='authors')
    op.alter_column('authors', 'name',
               existing_type=sa.VARBINARY(length=100),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('authors', 'mobile')
    # ### end Alembic commands ###
